### ISSUE TITLE
CT Designed API changes detected, please roll them back or revise the reference API

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/friction#310]
```
friction : phet-io-api-compatibility : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661305124647/friction/friction_en.html?continuousTest=%7B%22test%22%3A%5B%22friction%22%2C%22phet-io-api-compatibility%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1661305124647%22%2C%22timestamp%22%3A1661311267173%7D&ea&brand=phet-io&phetioStandalone&phetioCompareAPI&randomSeed=332211
Query: ea&brand=phet-io&phetioStandalone&phetioCompareAPI&randomSeed=332211
Uncaught Error: Assertion failed: Designed API changes detected, please roll them back or revise the reference API:

friction.frictionScreen.view.bottomBookNode.titleText.textProperty.phetioDocumentation changed from Property for the displayed text to

friction.frictionScreen.view.bottomBookNode.titleText.textProperty.phetioFeatured changed from true to false

friction.frictionScreen.view.bottomBookNode.titleText.textProperty.phetioReadOnly changed from false to true

friction.frictionScreen.view.bottomBookNode.titleText.textProperty.phetioTypeName changed from PropertyIO<StringIO> to LinkedElementIO

friction.frictionScreen.view.bottomBookNode.titleText.textProperty._data.initialState differs.
Expected:
{"units":null,"validValues":null,"value":"Physics"}
actual:
{"elementID":"friction.general.model.strings.friction.physicsStringProperty"}

friction.frictionScreen.view.topBookNode.titleText.textProperty.phetioDocumentation changed from Property for the displayed text to

friction.frictionScreen.view.topBookNode.titleText.textProperty.phetioFeatured changed from true to false

friction.frictionScreen.view.topBookNode.titleText.textProperty.phetioReadOnly changed from false to true

friction.frictionScreen.view.topBookNode.titleText.textProperty.phetioTypeName changed from PropertyIO<StringIO> to LinkedElementIO

friction.frictionScreen.view.topBookNode.titleText.textProperty._data.initialState differs.
Expected:
{"units":null,"validValues":null,"value":"Chemistry"}
actual:
{"elementID":"friction.general.model.strings.friction.chemistryStringProperty"}

Error: Assertion failed: Designed API changes detected, please roll them back or revise the reference API:
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661305124647/assert/js/assert.js:28:13)
at assert (phetioEngine.ts:365:22)
id: Bayes Puppeteer
Snapshot from 8/23/2022, 7:38:44 PM

----------------------------------

friction : phet-io-api-compatibility : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661305124647/friction/friction_en.html?continuousTest=%7B%22test%22%3A%5B%22friction%22%2C%22phet-io-api-compatibility%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1661305124647%22%2C%22timestamp%22%3A1661318762142%7D&ea&brand=phet-io&phetioStandalone&phetioCompareAPI&randomSeed=332211
Query: ea&brand=phet-io&phetioStandalone&phetioCompareAPI&randomSeed=332211
Uncaught Error: Assertion failed: Designed API changes detected, please roll them back or revise the reference API:

friction.frictionScreen.view.bottomBookNode.titleText.textProperty.phetioDocumentation changed from Property for the displayed text to

friction.frictionScreen.view.bottomBookNode.titleText.textProperty.phetioFeatured changed from true to false

friction.frictionScreen.view.bottomBookNode.titleText.textProperty.phetioReadOnly changed from false to true

friction.frictionScreen.view.bottomBookNode.titleText.textProperty.phetioTypeName changed from PropertyIO<StringIO> to LinkedElementIO

friction.frictionScreen.view.bottomBookNode.titleText.textProperty._data.initialState differs.
Expected:
{"units":null,"validValues":null,"value":"Physics"}
actual:
{"elementID":"friction.general.model.strings.friction.physicsStringProperty"}

friction.frictionScreen.view.topBookNode.titleText.textProperty.phetioDocumentation changed from Property for the displayed text to

friction.frictionScreen.view.topBookNode.titleText.textProperty.phetioFeatured changed from true to false

friction.frictionScreen.view.topBookNode.titleText.textProperty.phetioReadOnly changed from false to true

friction.frictionScreen.view.topBookNode.titleText.textProperty.phetioTypeName changed from PropertyIO<StringIO> to LinkedElementIO

friction.frictionScreen.view.topBookNode.titleText.textProperty._data.initialState differs.
Expected:
{"units":null,"validValues":null,"value":"Chemistry"}
actual:
{"elementID":"friction.general.model.strings.friction.chemistryStringProperty"}

Error: Assertion failed: Designed API changes detected, please roll them back or revise the reference API:
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661305124647/assert/js/assert.js:28:13)
at assert (phetioEngine.ts:365:22)
id: Bayes Puppeteer
Snapshot from 8/23/2022, 7:38:44 PM

----------------------------------

friction : phet-io-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661305124647/friction/friction_en.html?continuousTest=%7B%22test%22%3A%5B%22friction%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1661305124647%22%2C%22timestamp%22%3A1661311702555%7D&ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Query: ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: PhET-iO API error:
friction.frictionScreen.view.bottomBookNode.titleText.textProperty: 8. Any schema entries in the overrides file must be different from its baseline counterpart.
Error: Assertion failed: PhET-iO API error:
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661305124647/assert/js/assert.js:28:13)
at assert (phetioAPIValidation.ts:217:14)
at assertAPIError (phetioAPIValidation.ts:186:19)
at validateOverridesFile (phetioAPIValidation.ts:86:11)
at onSimStarted (phetioEngine.ts:382:28)
at listener (TinyEmitter.ts:95:8)
at emit (ReadOnlyProperty.ts:277:22)
at _notifyListeners (ReadOnlyProperty.ts:228:13)
at set (Property.ts:54:10)
at (Sim.ts:910:14)
id: Bayes Puppeteer
Snapshot from 8/23/2022, 7:38:44 PM

----------------------------------

friction : phet-io-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661305124647/friction/friction_en.html?continuousTest=%7B%22test%22%3A%5B%22friction%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1661305124647%22%2C%22timestamp%22%3A1661320349065%7D&ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Query: ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: PhET-iO API error:
friction.frictionScreen.view.bottomBookNode.titleText.textProperty: 8. Any schema entries in the overrides file must be different from its baseline counterpart.
Error: Assertion failed: PhET-iO API error:
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661305124647/assert/js/assert.js:28:13)
at assert (phetioAPIValidation.ts:217:14)
at assertAPIError (phetioAPIValidation.ts:186:19)
at validateOverridesFile (phetioAPIValidation.ts:86:11)
at onSimStarted (phetioEngine.ts:382:28)
at listener (TinyEmitter.ts:95:8)
at emit (ReadOnlyProperty.ts:277:22)
at _notifyListeners (ReadOnlyProperty.ts:228:13)
at set (Property.ts:54:10)
at (Sim.ts:910:14)
id: Bayes Puppeteer
Snapshot from 8/23/2022, 7:38:44 PM

----------------------------------

friction : phet-io-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661305124647/friction/friction_en.html?continuousTest=%7B%22test%22%3A%5B%22friction%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1661305124647%22%2C%22timestamp%22%3A1661333358783%7D&ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Query: ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: PhET-iO API error:
friction.frictionScreen.view.bottomBookNode.titleText.textProperty: 8. Any schema entries in the overrides file must be different from its baseline counterpart.
Error: Assertion failed: PhET-iO API error:
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661305124647/assert/js/assert.js:28:13)
at assert (phetioAPIValidation.ts:217:14)
at assertAPIError (phetioAPIValidation.ts:186:19)
at validateOverridesFile (phetioAPIValidation.ts:86:11)
at onSimStarted (phetioEngine.ts:382:28)
at listener (TinyEmitter.ts:95:8)
at emit (ReadOnlyProperty.ts:277:22)
at _notifyListeners (ReadOnlyProperty.ts:228:13)
at set (Property.ts:54:10)
at (Sim.ts:910:14)
id: Bayes Puppeteer
Snapshot from 8/23/2022, 7:38:44 PM

----------------------------------

friction : phet-io-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661305124647/friction/friction_en.html?continuousTest=%7B%22test%22%3A%5B%22friction%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1661305124647%22%2C%22timestamp%22%3A1661347785900%7D&ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Query: ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: PhET-iO API error:
friction.frictionScreen.view.bottomBookNode.titleText.textProperty: 8. Any schema entries in the overrides file must be different from its baseline counterpart.
Error: Assertion failed: PhET-iO API error:
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661305124647/assert/js/assert.js:28:13)
at assert (phetioAPIValidation.ts:217:14)
at assertAPIError (phetioAPIValidation.ts:186:19)
at validateOverridesFile (phetioAPIValidation.ts:86:11)
at onSimStarted (phetioEngine.ts:382:28)
at listener (TinyEmitter.ts:95:8)
at emit (ReadOnlyProperty.ts:277:22)
at _notifyListeners (ReadOnlyProperty.ts:228:13)
at set (Property.ts:54:10)
at (Sim.ts:910:14)
id: Bayes Puppeteer
Snapshot from 8/23/2022, 7:38:44 PM

----------------------------------

friction : phet-io-state-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661305124647/phet-io-wrappers/state/?sim=friction&phetioDebug=true&phetioWrapperDebug=true&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22friction%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1661305124647%22%2C%22timestamp%22%3A1661311341795%7D
Uncaught Error: Uncaught Error: Assertion failed: PhET-iO API error:
friction.frictionScreen.view.bottomBookNode.titleText.textProperty: 8. Any schema entries in the overrides file must be different from its baseline counterpart.
Error: Assertion failed: PhET-iO API error:
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661305124647/assert/js/assert.js:28:13)
at assert (phetioAPIValidation.ts:217:14)
at assertAPIError (phetioAPIValidation.ts:186:19)
at validateOverridesFile (phetioAPIValidation.ts:86:11)
at onSimStarted (phetioEngine.ts:382:28)
at listener (TinyEmitter.ts:95:8)
at emit (ReadOnlyProperty.ts:277:22)
at _notifyListeners (ReadOnlyProperty.ts:228:13)
at set (Property.ts:54:10)
at (Sim.ts:910:14)
id: Bayes Puppeteer
Snapshot from 8/23/2022, 7:38:44 PM

----------------------------------

friction : phet-io-state-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661305124647/phet-io-wrappers/state/?sim=friction&phetioDebug=true&phetioWrapperDebug=true&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22friction%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1661305124647%22%2C%22timestamp%22%3A1661319489962%7D
Uncaught Error: Uncaught Error: Assertion failed: PhET-iO API error:
friction.frictionScreen.view.bottomBookNode.titleText.textProperty: 8. Any schema entries in the overrides file must be different from its baseline counterpart.
Error: Assertion failed: PhET-iO API error:
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661305124647/assert/js/assert.js:28:13)
at assert (phetioAPIValidation.ts:217:14)
at assertAPIError (phetioAPIValidation.ts:186:19)
at validateOverridesFile (phetioAPIValidation.ts:86:11)
at onSimStarted (phetioEngine.ts:382:28)
at listener (TinyEmitter.ts:95:8)
at emit (ReadOnlyProperty.ts:277:22)
at _notifyListeners (ReadOnlyProperty.ts:228:13)
at set (Property.ts:54:10)
at (Sim.ts:910:14)
id: Bayes Puppeteer
Snapshot from 8/23/2022, 7:38:44 PM

----------------------------------

friction : phet-io-state-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661305124647/phet-io-wrappers/state/?sim=friction&phetioDebug=true&phetioWrapperDebug=true&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22friction%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1661305124647%22%2C%22timestamp%22%3A1661334241500%7D
Uncaught Error: Uncaught Error: Assertion failed: PhET-iO API error:
friction.frictionScreen.view.bottomBookNode.titleText.textProperty: 8. Any schema entries in the overrides file must be different from its baseline counterpart.
Error: Assertion failed: PhET-iO API error:
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661305124647/assert/js/assert.js:28:13)
at assert (phetioAPIValidation.ts:217:14)
at assertAPIError (phetioAPIValidation.ts:186:19)
at validateOverridesFile (phetioAPIValidation.ts:86:11)
at onSimStarted (phetioEngine.ts:382:28)
at listener (TinyEmitter.ts:95:8)
at emit (ReadOnlyProperty.ts:277:22)
at _notifyListeners (ReadOnlyProperty.ts:228:13)
at set (Property.ts:54:10)
at (Sim.ts:910:14)
id: Bayes Puppeteer
Snapshot from 8/23/2022, 7:38:44 PM

----------------------------------

friction : phet-io-state-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661305124647/phet-io-wrappers/state/?sim=friction&phetioDebug=true&phetioWrapperDebug=true&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22friction%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1661305124647%22%2C%22timestamp%22%3A1661347652880%7D
Uncaught Error: Uncaught Error: Assertion failed: PhET-iO API error:
friction.frictionScreen.view.bottomBookNode.titleText.textProperty: 8. Any schema entries in the overrides file must be different from its baseline counterpart.
Error: Assertion failed: PhET-iO API error:
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661305124647/assert/js/assert.js:28:13)
at assert (phetioAPIValidation.ts:217:14)
at assertAPIError (phetioAPIValidation.ts:186:19)
at validateOverridesFile (phetioAPIValidation.ts:86:11)
at onSimStarted (phetioEngine.ts:382:28)
at listener (TinyEmitter.ts:95:8)
at emit (ReadOnlyProperty.ts:277:22)
at _notifyListeners (ReadOnlyProperty.ts:228:13)
at set (Property.ts:54:10)
at (Sim.ts:910:14)
id: Bayes Puppeteer
Snapshot from 8/23/2022, 7:38:44 PM

----------------------------------

friction : phet-io-wrappers-tests : assert
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661305124647/phet-io-wrappers/phet-io-wrappers-tests.html?sim=friction&phetioDebug=true&phetioWrapperDebug=true
32 out of 33 tests passed. 1 failed.
SimTests: friction: event indexing failed:
Uncaught Error: Uncaught Error: Assertion failed: PhET-iO API error:
friction.frictionScreen.view.bottomBookNode.titleText.textProperty: 8. Any schema entries in the overrides file must be different from its baseline counterpart.
Error: Assertion failed: PhET-iO API error:
friction.frictionScreen.view.bottomBookNode.titleText.textProperty: 8. Any schema entries in the overrides file must be different from its baseline counterpart.
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661305124647/assert/js/assert.js:28:13)
at PhetioAPIValidation.assertAPIError (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661305124647/chipper/dist/js/tandem/js/phetioAPIValidation.js:184:15)
at PhetioAPIValidation.validateOverridesFile (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661305124647/chipper/dist/js/tandem/js/phetioAPIValidation.js:156:20)
at PhetioAPIValidation.onSimStarted (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661305124647/chipper/dist/js/tandem/js/phetioAPIValidation.js:62:12)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661305124647/chipper/dist/js/phet-io/js/phetioEngine.js:318:29
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661305124647/chipper/dist/js/axon/js/TinyEmitter.js:69:9)
at Property._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661305124647/chipper/dist/js/axon/js/ReadOnlyProperty.js:211:23)
at Property.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661305124647/chipper/dist/js/axon/js/ReadOnlyProperty.js:161:14)
at Property.set value [as value] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661305124647/chipper/dist/js/axon/js/Property.js:52:11)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661305124647/chipper/dist/js/joist/js/Sim.js:706:56

Uncaught Error: Uncaught Error: Assertion failed: PhET-iO API error:
friction.frictionScreen.view.bottomBookNode.titleText.textProperty: 8. Any schema entries in the overrides file must be different from its baseline counterpart.Error: Assertion failed: PhET-iO API error:
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661305124647/assert/js/assert.js:28:13)
at assert (phetioAPIValidation.ts:217:14)
at assertAPIError (phetioAPIValidation.ts:186:19)
at validateOverridesFile (phetioAPIValidation.ts:86:11)
at onSimStarted (phetioEngine.ts:382:28)
at listener (TinyEmitter.ts:95:8)
at emit (ReadOnlyProperty.ts:277:22)
at _notifyListeners (ReadOnlyProperty.ts:228:13)
at set (Property.ts:54:10)
at (Sim.ts:910:14)
id: Bayes Puppeteer
Snapshot from 8/23/2022, 7:38:44 PM

----------------------------------

friction : phet-io-wrappers-tests : no-assert
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661305124647/phet-io-wrappers/phet-io-wrappers-tests.html?sim=friction
30 out of 31 tests passed. 1 failed.
SimTests: friction: event indexing failed:
Uncaught Error: Uncaught Error: Assertion failed: PhET-iO API error:
friction.frictionScreen.view.bottomBookNode.titleText.textProperty: 8. Any schema entries in the overrides file must be different from its baseline counterpart.
Error: Assertion failed: PhET-iO API error:
friction.frictionScreen.view.bottomBookNode.titleText.textProperty: 8. Any schema entries in the overrides file must be different from its baseline counterpart.
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661305124647/assert/js/assert.js:28:13)
at PhetioAPIValidation.assertAPIError (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661305124647/chipper/dist/js/tandem/js/phetioAPIValidation.js:184:15)
at PhetioAPIValidation.validateOverridesFile (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661305124647/chipper/dist/js/tandem/js/phetioAPIValidation.js:156:20)
at PhetioAPIValidation.onSimStarted (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661305124647/chipper/dist/js/tandem/js/phetioAPIValidation.js:62:12)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661305124647/chipper/dist/js/phet-io/js/phetioEngine.js:318:29
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661305124647/chipper/dist/js/axon/js/TinyEmitter.js:69:9)
at Property._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661305124647/chipper/dist/js/axon/js/ReadOnlyProperty.js:211:23)
at Property.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661305124647/chipper/dist/js/axon/js/ReadOnlyProperty.js:161:14)
at Property.set value [as value] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661305124647/chipper/dist/js/axon/js/Property.js:52:11)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661305124647/chipper/dist/js/joist/js/Sim.js:706:56

Uncaught Error: Uncaught Error: Assertion failed: PhET-iO API error:
friction.frictionScreen.view.bottomBookNode.titleText.textProperty: 8. Any schema entries in the overrides file must be different from its baseline counterpart.Error: Assertion failed: PhET-iO API error:
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661305124647/assert/js/assert.js:28:13)
at assert (phetioAPIValidation.ts:217:14)
at assertAPIError (phetioAPIValidation.ts:186:19)
at validateOverridesFile (phetioAPIValidation.ts:86:11)
at onSimStarted (phetioEngine.ts:382:28)
at listener (TinyEmitter.ts:95:8)
at emit (ReadOnlyProperty.ts:277:22)
at _notifyListeners (ReadOnlyProperty.ts:228:13)
at set (Property.ts:54:10)
at (Sim.ts:910:14)
id: Bayes Puppeteer
Snapshot from 8/23/2022, 7:38:44 PM
```

**Comment by zepumph** [comment]
Fixed now
