### ISSUE TITLE
CT Failed validation for validators[0]: Number must be within rangeProperty value.

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/friction#313]
```
friction : fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1670220492854/friction/friction_en.html?continuousTest=%7B%22test%22%3A%5B%22friction%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1670220492854%22%2C%22timestamp%22%3A1670223055769%7D&brand=phet&ea&fuzz&memoryLimit=1000
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: validation failed:
Property value not valid: Failed validation for validators[0]: Number must be within rangeProperty value.: value failed isValidValue: NaN
prunedValidator:
[object Object]
Error: Assertion failed: validation failed:
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1670220492854/assert/js/assert.js:28:13)
at assert (validate.ts:25:16)
at validate (ReadOnlyProperty.ts:205:33)
at listener (TinyEmitter.ts:95:8)
at emit (ReadOnlyProperty.ts:311:22)
at _notifyListeners (ReadOnlyProperty.ts:262:13)
at unguardedSet (ReadOnlyProperty.ts:246:11)
at set (Property.ts:65:10)
at set (BookRubSoundGenerator.js:53:36)
at listener (TinyEmitter.ts:95:8)
id: Bayes Puppeteer
Snapshot from 12/4/2022, 11:08:12 PM

----------------------------------

friction : fuzz : unbuilt : assertSlow
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1670220492854/friction/friction_en.html?continuousTest=%7B%22test%22%3A%5B%22friction%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22assertSlow%22%5D%2C%22snapshotName%22%3A%22snapshot-1670220492854%22%2C%22timestamp%22%3A1670234097291%7D&brand=phet&eall&fuzz&memoryLimit=1000
Query: brand=phet&eall&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: reentry detected, value=Vector2(600, 65), oldValue=Vector2(600, 65)
Error: Assertion failed: reentry detected, value=Vector2(600, 65), oldValue=Vector2(600, 65)
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1670220492854/assert/js/assert.js:28:13)
at assert (ReadOnlyProperty.ts:308:14)
at _notifyListeners (ReadOnlyProperty.ts:262:13)
at unguardedSet (ReadOnlyProperty.ts:246:11)
at set (Property.ts:54:10)
at (DragListener.ts:696:34)
at reposition (DragListener.ts:362:11)
at callback (PressListener.ts:729:16)
at apply (PhetioAction.ts:157:16)
at execute (PressListener.ts:485:22)
id: Bayes Puppeteer
Snapshot from 12/4/2022, 11:08:12 PM

----------------------------------

friction : interactive-description-fuzz-fuzzBoard-combo : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1670220492854/friction/friction_en.html?continuousTest=%7B%22test%22%3A%5B%22friction%22%2C%22interactive-description-fuzz-fuzzBoard-combo%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1670220492854%22%2C%22timestamp%22%3A1670223634797%7D&brand=phet&ea&supportsInteractiveDescription=true&fuzz&fuzzBoard&memoryLimit=1000
Query: brand=phet&ea&supportsInteractiveDescription=true&fuzz&fuzzBoard&memoryLimit=1000
Uncaught Error: Assertion failed: validation failed:
Property value not valid: Failed validation for validators[0]: Number must be within rangeProperty value.: value failed isValidValue: NaN
prunedValidator:
[object Object]
Error: Assertion failed: validation failed:
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1670220492854/assert/js/assert.js:28:13)
at assert (validate.ts:25:16)
at validate (ReadOnlyProperty.ts:205:33)
at listener (TinyEmitter.ts:95:8)
at emit (ReadOnlyProperty.ts:311:22)
at _notifyListeners (ReadOnlyProperty.ts:262:13)
at unguardedSet (ReadOnlyProperty.ts:246:11)
at set (Property.ts:65:10)
at set (BookRubSoundGenerator.js:53:36)
at listener (TinyEmitter.ts:95:8)
id: Bayes Puppeteer
Snapshot from 12/4/2022, 11:08:12 PM

----------------------------------

friction : interactive-description-fuzz-fuzzBoard-combo : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1670220492854/friction/friction_en.html?continuousTest=%7B%22test%22%3A%5B%22friction%22%2C%22interactive-description-fuzz-fuzzBoard-combo%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1670220492854%22%2C%22timestamp%22%3A1670236060783%7D&brand=phet&ea&supportsInteractiveDescription=true&fuzz&fuzzBoard&memoryLimit=1000
Query: brand=phet&ea&supportsInteractiveDescription=true&fuzz&fuzzBoard&memoryLimit=1000
Uncaught Error: Assertion failed: validation failed:
Property value not valid: Failed validation for validators[0]: Number must be within rangeProperty value.: value failed isValidValue: NaN
prunedValidator:
[object Object]
Error: Assertion failed: validation failed:
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1670220492854/assert/js/assert.js:28:13)
at assert (validate.ts:25:16)
at validate (ReadOnlyProperty.ts:205:33)
at listener (TinyEmitter.ts:95:8)
at emit (ReadOnlyProperty.ts:311:22)
at _notifyListeners (ReadOnlyProperty.ts:262:13)
at unguardedSet (ReadOnlyProperty.ts:246:11)
at set (Property.ts:65:10)
at set (BookRubSoundGenerator.js:53:36)
at listener (TinyEmitter.ts:95:8)
id: Bayes Puppeteer
Snapshot from 12/4/2022, 11:08:12 PM

----------------------------------

friction : interactive-description-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1670220492854/friction/friction_en.html?continuousTest=%7B%22test%22%3A%5B%22friction%22%2C%22interactive-description-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1670220492854%22%2C%22timestamp%22%3A1670223510737%7D&brand=phet&ea&fuzz&supportsInteractiveDescription=true&memoryLimit=1000
Query: brand=phet&ea&fuzz&supportsInteractiveDescription=true&memoryLimit=1000
Uncaught Error: Assertion failed: reentry detected, value=Vector2(600, 45), oldValue=Vector2(600, 45)
Error: Assertion failed: reentry detected, value=Vector2(600, 45), oldValue=Vector2(600, 45)
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1670220492854/assert/js/assert.js:28:13)
at assert (ReadOnlyProperty.ts:308:14)
at _notifyListeners (ReadOnlyProperty.ts:262:13)
at unguardedSet (ReadOnlyProperty.ts:246:11)
at set (Property.ts:54:10)
at (DragListener.ts:696:34)
at reposition (DragListener.ts:362:11)
at callback (PressListener.ts:729:16)
at apply (PhetioAction.ts:157:16)
at execute (PressListener.ts:485:22)
id: Bayes Puppeteer
Snapshot from 12/4/2022, 11:08:12 PM

----------------------------------

friction : interactive-description-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1670220492854/friction/friction_en.html?continuousTest=%7B%22test%22%3A%5B%22friction%22%2C%22interactive-description-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1670220492854%22%2C%22timestamp%22%3A1670235982976%7D&brand=phet&ea&fuzz&supportsInteractiveDescription=true&memoryLimit=1000
Query: brand=phet&ea&fuzz&supportsInteractiveDescription=true&memoryLimit=1000
Uncaught Error: Assertion failed: reentry detected, value=Vector2(463.5, 25), oldValue=Vector2(600, 25)
Error: Assertion failed: reentry detected, value=Vector2(463.5, 25), oldValue=Vector2(600, 25)
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1670220492854/assert/js/assert.js:28:13)
at assert (ReadOnlyProperty.ts:308:14)
at _notifyListeners (ReadOnlyProperty.ts:262:13)
at unguardedSet (ReadOnlyProperty.ts:246:11)
at set (Property.ts:54:10)
at (DragListener.ts:696:34)
at reposition (DragListener.ts:305:15)
at apply (PhetioAction.ts:157:16)
at execute (DragListener.ts:460:21)
at drag (PressListener.ts:897:13)
id: Bayes Puppeteer
Snapshot from 12/4/2022, 11:08:12 PM

----------------------------------

friction : interactive-description-fuzzBoard : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1670220492854/friction/friction_en.html?continuousTest=%7B%22test%22%3A%5B%22friction%22%2C%22interactive-description-fuzzBoard%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1670220492854%22%2C%22timestamp%22%3A1670236748626%7D&brand=phet&ea&fuzzBoard&supportsInteractiveDescription=true&memoryLimit=1000
Query: brand=phet&ea&fuzzBoard&supportsInteractiveDescription=true&memoryLimit=1000
Uncaught Error: Assertion failed: validation failed:
Property value not valid: Failed validation for validators[0]: Number must be within rangeProperty value.: value failed isValidValue: NaN
prunedValidator:
[object Object]
Error: Assertion failed: validation failed:
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1670220492854/assert/js/assert.js:28:13)
at assert (validate.ts:25:16)
at validate (ReadOnlyProperty.ts:205:33)
at listener (TinyEmitter.ts:95:8)
at emit (ReadOnlyProperty.ts:311:22)
at _notifyListeners (ReadOnlyProperty.ts:262:13)
at unguardedSet (ReadOnlyProperty.ts:246:11)
at set (Property.ts:65:10)
at set (BookRubSoundGenerator.js:53:36)
at listener (TinyEmitter.ts:95:8)
id: Bayes Puppeteer
Snapshot from 12/4/2022, 11:08:12 PM

----------------------------------

friction : multitouch-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1670220492854/friction/friction_en.html?continuousTest=%7B%22test%22%3A%5B%22friction%22%2C%22multitouch-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1670220492854%22%2C%22timestamp%22%3A1670223101019%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Uncaught Error: Assertion failed: reentry detected, value=Vector2(-306, -27.5), oldValue=Vector2(-306, -27.499999999999993)
Error: Assertion failed: reentry detected, value=Vector2(-306, -27.5), oldValue=Vector2(-306, -27.499999999999993)
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1670220492854/assert/js/assert.js:28:13)
at assert (ReadOnlyProperty.ts:308:14)
at _notifyListeners (ReadOnlyProperty.ts:262:13)
at unguardedSet (ReadOnlyProperty.ts:246:11)
at set (Property.ts:54:10)
at (DragListener.ts:696:34)
at reposition (DragListener.ts:362:11)
at callback (PressListener.ts:729:16)
at apply (PhetioAction.ts:157:16)
at execute (PressListener.ts:485:22)
id: Bayes Puppeteer
Snapshot from 12/4/2022, 11:08:12 PM

----------------------------------

friction : pan-and-zoom-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1670220492854/friction/friction_en.html?continuousTest=%7B%22test%22%3A%5B%22friction%22%2C%22pan-and-zoom-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1670220492854%22%2C%22timestamp%22%3A1670222404992%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Uncaught Error: Assertion failed: reentry detected, value=Vector2(600, 14.75), oldValue=Vector2(600, 23)
Error: Assertion failed: reentry detected, value=Vector2(600, 14.75), oldValue=Vector2(600, 23)
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1670220492854/assert/js/assert.js:28:13)
at assert (ReadOnlyProperty.ts:308:14)
at _notifyListeners (ReadOnlyProperty.ts:262:13)
at unguardedSet (ReadOnlyProperty.ts:246:11)
at set (Property.ts:54:10)
at (DragListener.ts:696:34)
at reposition (DragListener.ts:305:15)
at apply (PhetioAction.ts:157:16)
at execute (DragListener.ts:460:21)
at drag (PressListener.ts:897:13)
id: Bayes Puppeteer
Snapshot from 12/4/2022, 11:08:12 PM

----------------------------------

friction : pan-and-zoom-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1670220492854/friction/friction_en.html?continuousTest=%7B%22test%22%3A%5B%22friction%22%2C%22pan-and-zoom-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1670220492854%22%2C%22timestamp%22%3A1670235774171%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Uncaught Error: Assertion failed: reentry detected, value=Vector2(420.8080922488351, -45), oldValue=Vector2(600, -1.5)
Error: Assertion failed: reentry detected, value=Vector2(420.8080922488351, -45), oldValue=Vector2(600, -1.5)
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1670220492854/assert/js/assert.js:28:13)
at assert (ReadOnlyProperty.ts:308:14)
at _notifyListeners (ReadOnlyProperty.ts:262:13)
at unguardedSet (ReadOnlyProperty.ts:246:11)
at set (Property.ts:54:10)
at (DragListener.ts:696:34)
at reposition (DragListener.ts:305:15)
at apply (PhetioAction.ts:157:16)
at execute (DragListener.ts:460:21)
at drag (PressListener.ts:897:13)
id: Bayes Puppeteer
Snapshot from 12/4/2022, 11:08:12 PM

----------------------------------

friction : voicing-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1670220492854/friction/friction_en.html?continuousTest=%7B%22test%22%3A%5B%22friction%22%2C%22voicing-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1670220492854%22%2C%22timestamp%22%3A1670223396074%7D&brand=phet&ea&fuzz&voicingInitiallyEnabled&memoryLimit=1000
Query: brand=phet&ea&fuzz&voicingInitiallyEnabled&memoryLimit=1000
Uncaught Error: Assertion failed: reentry detected, value=Vector2(600, 45), oldValue=Vector2(600, 45)
Error: Assertion failed: reentry detected, value=Vector2(600, 45), oldValue=Vector2(600, 45)
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1670220492854/assert/js/assert.js:28:13)
at assert (ReadOnlyProperty.ts:308:14)
at _notifyListeners (ReadOnlyProperty.ts:262:13)
at unguardedSet (ReadOnlyProperty.ts:246:11)
at set (Property.ts:54:10)
at (DragListener.ts:696:34)
at reposition (DragListener.ts:362:11)
at callback (PressListener.ts:729:16)
at apply (PhetioAction.ts:157:16)
at execute (PressListener.ts:485:22)
id: Bayes Puppeteer
Snapshot from 12/4/2022, 11:08:12 PM

----------------------------------

friction : voicing-fuzzBoard : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1670220492854/friction/friction_en.html?continuousTest=%7B%22test%22%3A%5B%22friction%22%2C%22voicing-fuzzBoard%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1670220492854%22%2C%22timestamp%22%3A1670235872167%7D&brand=phet&ea&fuzzBoard&voicingInitiallyEnabled&memoryLimit=1000
Query: brand=phet&ea&fuzzBoard&voicingInitiallyEnabled&memoryLimit=1000
Uncaught Error: Assertion failed: reentry detected, value=Vector2(-425, -20), oldValue=Vector2(-425, -30)
Error: Assertion failed: reentry detected, value=Vector2(-425, -20), oldValue=Vector2(-425, -30)
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1670220492854/assert/js/assert.js:28:13)
at assert (ReadOnlyProperty.ts:308:14)
at _notifyListeners (ReadOnlyProperty.ts:262:13)
at unguardedSet (ReadOnlyProperty.ts:246:11)
at set (Property.ts:65:10)
at set (KeyboardDragListener.ts:802:35)
at updatePosition (KeyboardDragListener.ts:677:13)
at listener (TinyEmitter.ts:95:8)
at emit (Sim.ts:422:16)
at apply (PhetioAction.ts:157:16)
id: Bayes Puppeteer
Snapshot from 12/4/2022, 11:08:12 PM

----------------------------------

friction : xss-fuzz
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1670220492854/friction/friction_en.html?continuousTest=%7B%22test%22%3A%5B%22friction%22%2C%22xss-fuzz%22%5D%2C%22snapshotName%22%3A%22snapshot-1670220492854%22%2C%22timestamp%22%3A1670225080252%7D&brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Query: brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Uncaught Error: Assertion failed: validation failed:
Property value not valid: Failed validation for validators[0]: Number must be within rangeProperty value.: value failed isValidValue: NaN
prunedValidator:
[object Object]
Error: Assertion failed: validation failed:
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1670220492854/assert/js/assert.js:28:13)
at assert (validate.ts:25:16)
at validate (ReadOnlyProperty.ts:205:33)
at listener (TinyEmitter.ts:95:8)
at emit (ReadOnlyProperty.ts:311:22)
at _notifyListeners (ReadOnlyProperty.ts:262:13)
at unguardedSet (ReadOnlyProperty.ts:246:11)
at set (Property.ts:65:10)
at set (BookRubSoundGenerator.js:53:36)
at listener (TinyEmitter.ts:95:8)
id: Bayes Puppeteer
Snapshot from 12/4/2022, 11:08:12 PM

----------------------------------

friction : xss-fuzz
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1670220492854/friction/friction_en.html?continuousTest=%7B%22test%22%3A%5B%22friction%22%2C%22xss-fuzz%22%5D%2C%22snapshotName%22%3A%22snapshot-1670220492854%22%2C%22timestamp%22%3A1670236217014%7D&brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Query: brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Uncaught Error: Assertion failed: validation failed:
Property value not valid: Failed validation for validators[0]: Number must be within rangeProperty value.: value failed isValidValue: NaN
prunedValidator:
[object Object]
Error: Assertion failed: validation failed:
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1670220492854/assert/js/assert.js:28:13)
at assert (validate.ts:25:16)
at validate (ReadOnlyProperty.ts:205:33)
at listener (TinyEmitter.ts:95:8)
at emit (ReadOnlyProperty.ts:311:22)
at _notifyListeners (ReadOnlyProperty.ts:262:13)
at unguardedSet (ReadOnlyProperty.ts:246:11)
at set (Property.ts:65:10)
at set (BookRubSoundGenerator.js:53:36)
at listener (TinyEmitter.ts:95:8)
id: Bayes Puppeteer
Snapshot from 12/4/2022, 11:08:12 PM
```

**Comment by zepumph** [comment]
From https://github.com/phetsims/axon/issues/425

**Comment by zepumph** [comment]
Fixed on master
