### ISSUE TITLE
CT Cannot read properties of undefined (reading 'domEvent')

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/friction#342]
```
friction : interactive-description-fuzz-fuzzBoard-combo : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1679652151654/friction/friction_en.html?continuousTest=%7B%22test%22%3A%5B%22friction%22%2C%22interactive-description-fuzz-fuzzBoard-combo%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1679652151654%22%2C%22timestamp%22%3A1679654645386%7D&brand=phet&ea&supportsInteractiveDescription=true&fuzz&fuzzBoard&memoryLimit=1000
Query: brand=phet&ea&supportsInteractiveDescription=true&fuzz&fuzzBoard&memoryLimit=1000
Uncaught TypeError: Cannot read properties of undefined (reading 'domEvent')
TypeError: Cannot read properties of undefined (reading 'domEvent')
at domEvent (FrictionKeyboardDragListener.js:37:43)
at _end (KeyboardDragListener.ts:1039:24)
at interrupt (GrabDragInteraction.js:691:74)
at Array.forEach
at forEach (GrabDragInteraction.js:691:22)
at baseInteractionUpdate (GrabDragInteraction.js:650:9)
at turnToGrabbable (GrabDragInteraction.js:616:9)
at releaseDraggable (GrabDragInteraction.js:506:15)
at inputEvent (Input.ts:1914:69)
at dispatchToListeners (Input.ts:1954:11)
id: Bayes Puppeteer
Snapshot from 3/24/2023, 4:02:31 AM

----------------------------------

friction : interactive-description-fuzzBoard : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1679652151654/friction/friction_en.html?continuousTest=%7B%22test%22%3A%5B%22friction%22%2C%22interactive-description-fuzzBoard%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1679652151654%22%2C%22timestamp%22%3A1679654651198%7D&brand=phet&ea&fuzzBoard&supportsInteractiveDescription=true&memoryLimit=1000
Query: brand=phet&ea&fuzzBoard&supportsInteractiveDescription=true&memoryLimit=1000
Uncaught TypeError: Cannot read properties of undefined (reading 'domEvent')
TypeError: Cannot read properties of undefined (reading 'domEvent')
at domEvent (FrictionKeyboardDragListener.js:37:43)
at _end (KeyboardDragListener.ts:1039:24)
at interrupt (GrabDragInteraction.js:691:74)
at Array.forEach
at forEach (GrabDragInteraction.js:691:22)
at baseInteractionUpdate (GrabDragInteraction.js:650:9)
at turnToGrabbable (GrabDragInteraction.js:616:9)
at releaseDraggable (GrabDragInteraction.js:506:15)
at inputEvent (Input.ts:1914:69)
at dispatchToListeners (Input.ts:1954:11)
id: Bayes Puppeteer
Snapshot from 3/24/2023, 4:02:31 AM

----------------------------------

friction : voicing-fuzzBoard : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1679652151654/friction/friction_en.html?continuousTest=%7B%22test%22%3A%5B%22friction%22%2C%22voicing-fuzzBoard%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1679652151654%22%2C%22timestamp%22%3A1679655250605%7D&brand=phet&ea&fuzzBoard&voicingInitiallyEnabled&memoryLimit=1000
Query: brand=phet&ea&fuzzBoard&voicingInitiallyEnabled&memoryLimit=1000
Uncaught TypeError: Cannot read properties of undefined (reading 'domEvent')
TypeError: Cannot read properties of undefined (reading 'domEvent')
at domEvent (FrictionKeyboardDragListener.js:37:43)
at _end (KeyboardDragListener.ts:1039:24)
at interrupt (GrabDragInteraction.js:691:74)
at Array.forEach
at forEach (GrabDragInteraction.js:691:22)
at baseInteractionUpdate (GrabDragInteraction.js:650:9)
at turnToGrabbable (GrabDragInteraction.js:616:9)
at releaseDraggable (GrabDragInteraction.js:506:15)
at inputEvent (Input.ts:1914:69)
at dispatchToListeners (Input.ts:1954:11)
id: Bayes Puppeteer
Snapshot from 3/24/2023, 4:02:31 AM
```

**Comment by zepumph** [comment]
Ahh thanks yes, from https://github.com/phetsims/scenery/issues/1285. CT should clean it up.

**Comment by zepumph** [comment]
It's cleaned up.
